services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - '5000:80'

  core:
    build:
      context: .
      dockerfile: core/Dockerfile
    ports:
      - '8000:8000'
